DELETE {
  GRAPH ?g {
    ?subject ?subjectP ?subjectO
  }
}
WHERE {
  VALUES ?besluitTypeUri {
    <https://data.vlaanderen.be/id/concept/BesluitDocumentType/672bf096-dccd-40af-ab60-bd7de15cc461>
  }
  VALUES ?sentByUri {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/f9cac08a-13c1-49da-9bcb-f650b0604054>
  }
  GRAPH ?g {
    ?submission a <http://rdf.myexperiment.org/ontologies/base/Submission>;
      <http://www.w3.org/ns/prov#generated> ?formData;
      <http://purl.org/pav/createdBy>/<http://data.vlaanderen.be/ns/besluit#classificatie> ?sentByUri;
                <http://purl.org/dc/terms/subject> ?subject.
    ?formData <http://mu.semte.ch/vocabularies/ext/decisionType> ?besluitTypeUri.
    ?subject ?subjectP ?subjectO.
  }
}