DELETE {
  GRAPH ?g {
    ?submission ?submissionP ?submissionO.
    ?formData ?formDataP ?formDataO.
  }
}
WHERE {
  VALUES ?besluitTypeUri {
    <https://data.vlaanderen.be/id/concept/BesluitType/54b61cbd-349f-41c4-9c8a-7e8e67d08347>
  }
  VALUES ?sentByUri {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86>
  }
  GRAPH ?g {
    ?submission a <http://rdf.myexperiment.org/ontologies/base/Submission>;
                <http://www.w3.org/ns/prov#generated> ?formData;
        	<http://purl.org/pav/createdBy> ?createdBy;
                ?submissionP ?submissionO.

    ?formData <http://mu.semte.ch/vocabularies/ext/decisionType> ?besluitTypeUri;
              ?formDataP ?formDataO.

    ?createdBy <http://data.vlaanderen.be/ns/besluit#classificatie> ?sentByUri.
  }
}

