DELETE {
  GRAPH ?g {
    ?submission ?submissionP ?submissionO.
    ?subject ?subjectP ?subjectO.
    ?formData ?formDataP ?formDataO.
    ?remoteDataObject ?remoteDataObjectP ?remoteDataObjectO.
  }
}
WHERE {
  VALUES ?besluitTypeUri {
    <https://data.vlaanderen.be/id/concept/BesluitDocumentType/18833df2-8c9e-4edd-87fd-b5c252337349>
    <https://data.vlaanderen.be/id/concept/BesluitDocumentType/ce569d3d-25ff-4ce9-a194-e77113597e29>
    <https://data.vlaanderen.be/id/concept/BesluitDocumentType/2c9ada23-1229-4c7e-a53e-acddc9014e4e>
  }
  VALUES ?sentByUri {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/f9cac08a-13c1-49da-9bcb-f650b0604054>
  }
  GRAPH ?g {
    ?submission a <http://rdf.myexperiment.org/ontologies/base/Submission>;
                <http://www.w3.org/ns/prov#generated> ?formData;
        	<http://purl.org/pav/createdBy> ?createdBy;
                ?submissionP ?submissionO;
                <http://purl.org/dc/terms/subject> ?subject.

    ?formData <http://mu.semte.ch/vocabularies/ext/decisionType> ?besluitTypeUri;
              ?formDataP ?formDataO;
              <http://purl.org/dc/terms/hasPart> ?remoteDataObject.

    ?subject ?subjectP ?subjectO.
    ?remoteDataObject ?remoteDataObjectP ?remoteDataObjectO.
    ?createdBy <http://data.vlaanderen.be/ns/besluit#classificatie> ?sentByUri.
  }
}