services:
  identifier:
    ports:
      - "81:80"
  mocklogin:
    image: lblod/mock-login-service:0.7.0
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b" # ABB
  virtuoso:
    ports:
      - "8891:8890"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    restart: "no"
  tika:
    restart: "no"
  search:
    restart: "no"
    environment:
      NUMBER_OF_THREADS: 4 # overwrite for development
      JRUBY_OPTIONS: "-J-Xmx8g" # overwrite for development
  worship-decisions-cross-reference:
    restart: "no"
  op-public-consumer:
    restart: "no"
