PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?bestuurseenheid ext:kbonummer ?kboNummer.
  }
} WHERE {
  ?bestuurseenheid
    a besluit:Bestuurseenheid ;
    adms:identifier ?identifier.

  ?identifier
    skos:notation "KBO nummer";
    generiek:gestructureerdeIdentificator ?gestructureerdeIdentificator.

  ?gestructureerdeIdentificator
    generiek:lokaleIdentificator ?kboNummer.
}
