PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX meb: <http://rdf.myexperiment.org/ontologies/base/>

DELETE {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> ?classP ?classO .
    ?classS ?classRP <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> .
    ?submission ?p ?o .
    ?submissionS ?rP ?submission .
  }
} WHERE {
  GRAPH ?g {
    ?submission a meb:Submission .
    ?submission <http://purl.org/pav/createdBy> ?organization .
    ?organization besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> .

    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> ?classP ?classO .
    ?classS ?classRP <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> .
    ?submission ?p ?o .
    ?submissionS ?rP ?submission .
  }
}