PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>

CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a besluit:Bestuurseenheid;
    ?p ?o.

  FILTER (?p IN (
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>,
    mu:uuid,
    skos:prefLabel,
    besluit:werkingsgebied,
    besluit:classificatie,
    dct:identifier,
    skos:altLabel,
    ere:betrokkenBestuur,
    org:hasPrimarySite
  ))
}
