CONSTRUCT {
  ?s ?p ?o .
}  
WHERE {
  ?s ?p ?o .

  FILTER EXISTS {
    ?s a ?type .

    VALUES ?type {
      <http://www.w3.org/2004/02/skos/core#Concept>
      <http://mu.semte.ch/vocabularies/ext/BestuursorgaanClassificatieCode>
      <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode>
      <http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode>
      <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode>
    }
  }
}
