DELETE {
 GRAPH ?g {
   ?s <http://purl.org/dc/terms/identifier> """OVO028736""".
 }
}
INSERT {
 GRAPH ?g {
   ?s <http://purl.org/dc/terms/identifier> """OVO036372""".
 }
}
WHERE {
  BIND(<http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> as ?s)
  GRAPH ?g {
    ?s <http://purl.org/dc/terms/identifier> ?o.
  }
}